<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\..\common.props" />
    <Import Project="..\..\..\configureawait.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" />
        <PackageReference Include="Volo.Abp.Authorization" />
        <PackageReference Include="Volo.Abp.SettingManagement.Application.Contracts" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Localization\Resources\AntDesignThemeManagement\*.json" />
        <Content Remove="Localization\Resources\AntDesignThemeManagement\*.json" />
    </ItemGroup>

</Project>
