<Project Sdk="Microsoft.NET.Sdk.Razor">

    <Import Project="..\..\..\common.props" />
    <Import Project="..\..\..\configureawait.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Lsw.Abp.AntDesignThemeManagement.Application\Lsw.Abp.AntDesignThemeManagement.Application.csproj" />
        <ProjectReference Include="..\Lsw.Abp.AntDesignThemeManagement.Blazor\Lsw.Abp.AntDesignThemeManagement.Blazor.csproj" />
        <ProjectReference Include="..\..\AntDesignTheme\Lsw.Abp.AspnetCore.Components.Server.AntDesignTheme\Lsw.Abp.AspnetCore.Components.Server.AntDesignTheme.csproj" />
    </ItemGroup>

</Project>
